# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  compatibility:
    runs-on: ubuntu-latest

    name: testing node@${{ matrix.node-version }}, redis@${{ matrix.redis-version }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        redis-version: [6, 7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./package.json

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start DynamoDB local
        uses: rrainn/dynamodb-action@v3.0.0
        
      - run: npm install
      - run: npm run test
